project:
    name: serverless-operator
    # When bumping the Operator to a new version (major and minor), make sure to also update
    # all components in `dependencies.previous` to the same versions as `dependencies` in the same PR.
    # Otherwise, the upgrade tests will not pass, as we have a different SO version with the same bundle contents.
    # Also make sure to update values under `olm.previous` by copying from `olm.replaces` and `olm.skipRange`.
    version: 1.31.1
olm:
    replaces: 1.31.0
    skipRange: '>=1.31.0 <1.31.1'
    channels:
        default: 'stable'
        list:
            - stable
            - stable-1.29
            - stable-1.30
            - stable-1.31
    previous:
        replaces: 1.30.0
        skipRange: '>=1.30.0 <1.31.0'
requirements:
    kube:
        # The min version validation in `vendor/knative.dev/pkg/version/version.go`
        # is ignored as it is overridden by fake version via KUBERNETES_MIN_VERSION.
        # This value is used for CSV's min version validation.
        minVersion: 1.24.0
    golang: '1.19'
    nodejs: 16.x
    ocpVersion:
        min: '4.11'
        max: '4.13'
        label: 'v4.11'
dependencies:
    serving: knative-v1.10
    # serving midstream branch name
    serving_artifacts_branch: release-v1.10
    # versions for networking components
    kourier: knative-v1.10
    net_kourier_artifacts_branch: release-v1.10
    net_istio: knative-v1.10
    net_istio_artifacts_branch: release-v1.10
    redhat-knative-istio-authz-chart: 1.31.0
    maistra: 2.4-latest
    eventing: knative-v1.10
    # eventing core midstream branch name
    eventing_artifacts_branch: release-v1.10
    # eventing-kafka-broker promotion tag
    eventing_kafka_broker: knative-v1.10
    # eventing-kafka-broker midstream branch or commit
    eventing_kafka_broker_artifacts_branch: release-v1.10
    # eventing-istio promotion tag
    eventing_istio: knative-v1.10
    # eventing-istio midstream branch or commit
    eventing_istio_artifacts_branch: release-v1.10
    cli: 1.10.0
    func:
        util: quay.io/boson/alpine-socat:1.7.4.3-r1-non-root
        tekton_s2i: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:6a6025914296a62fdf2092c3a40011bd9b966a6806b094d51eec5e1bd5026ef4
        tekton_buildah: registry.redhat.io/rhel8/buildah@sha256:b48f410efa0ff8ab0db6ead420a5d8d866d64af846fece5efb185230d7ecf591
        nodejs_16: registry.access.redhat.com/ubi8/nodejs-16@sha256:f90b28179d1d5de68d42ef1a9166d70a9dfea85a1c6a4bf12dce2c59eeb2fbb1
        openjdk_17: registry.access.redhat.com/ubi8/openjdk-17@sha256:a8165bc2cd5051a96d6937e25ed03155bbd4b731da6e58cebfe2ea83209c16d8
        python-39: registry.access.redhat.com/ubi8/python-39@sha256:4f35cbcc6f4e108c69f7d2b70cce5afb138741b0c961506376d524e001b922f4
    operator: 1.10.0
    # Previous versions required for downgrade testing
    previous:
        serving: knative-v1.10
        eventing: knative-v1.10
        eventing_kafka_broker: knative-v1.10
upgrade_sequence:
    - csv: serverless-operator.v1.29.0
    - csv: serverless-operator.v1.30.0
    - csv: serverless-operator.v1.31.0
